- name: install dispatch component
  hosts: dispatch
  become: yes
  tasks: 
  - name: install golang
    ansible.builtin.dnf:
      name: golang
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  
  
    