- name: user
  hosts: user
  become: yes
  tasks:
  - name: disable old nodejs and enable new js
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download user
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: extract user application
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: Copy user service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: deamon reload and start 
    ansible.builtin.systemd_service:
      daemon_reload: true

  # lets start after the data reload

  - name: mongod repo Copy
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
  
  - name: get the categories count
    ansible.builtin.command: mongo --host mongodb.cbdhaba.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count

  #- name: print he count
  #  ansible.builtin.debug:
   #   msg: "user_count: {{product_count}}"

  - name: load user data
    ansible.builtin.command: mongo --host mongodb.cbdhaba.online < /app/schema/user.js
    when: product_count.stdout == "0" # keep double quotes

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes



