- name: web
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: Enable nginx and start
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes

  - name: Recursively remove directory
    ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download web fronted content
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp

  - name: extract web frontend content
    ansible.builtin.unarchive:
      src: /usr/share/nginx/html
      dest: /tmp/web.zip
      remote_src: yes

  - name: Copy Roboshop conf
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

  - name: Start and enabled nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes


  

